# Generated by Django 3.2.13 on 2022-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='writing',
            name='content',
            field=models.TextField(verbose_name='내용을 입력하세요:'),
        ),
    ]
