# Generated by Django 3.2.13 on 2022-05-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20220522_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
