# Generated by Django 3.2.13 on 2022-05-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_writing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='technical_field',
            field=models.CharField(choices=[('other', '기타'), ('app', '앱'), ('web', '웹'), ('game', '게임'), ('ai', '인공지능')], default='', max_length=80),
        ),
    ]
