# Generated by Django 3.2.13 on 2022-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_writing_technical_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writing',
            name='subject',
        ),
        migrations.AddField(
            model_name='writing',
            name='team',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='writing',
            name='topic_area',
            field=models.CharField(choices=[('공공/교통', '공공/교통'), ('생활', '생활'), ('의료', '의료'), ('업무', '업무'), ('금융/핀테크', '금융/핀테크'), ('유통/쇼핑', '유통/쇼핑'), ('엔터테인먼트', '엔터테인먼트'), ('교육', '교육')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='writing',
            name='content',
            field=models.TextField(verbose_name='프로젝트 개요서 첨부'),
        ),
        migrations.AlterField(
            model_name='writing',
            name='technical_field',
            field=models.CharField(choices=[('앱', '앱'), ('기타', '기타'), ('인공지능', '인공지능'), ('게임', '게임'), ('웹', '웹')], default='', max_length=80),
        ),
    ]
