# Generated by Django 3.2.13 on 2022-05-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20220522_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='technical_field',
            field=models.CharField(choices=[('인공지능', '인공지능'), ('웹', '웹'), ('게임', '게임'), ('앱', '앱'), ('기타', '기타')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='writing',
            name='topic_area',
            field=models.CharField(choices=[('엔터테인먼트', '엔터테인먼트'), ('의료', '의료'), ('금융/핀테크', '금융/핀테크'), ('생활', '생활'), ('유통/쇼핑', '유통/쇼핑'), ('공공/교통', '공공/교통'), ('교육', '교육'), ('업무', '업무')], default='', max_length=80),
        ),
    ]
