# Generated by Django 3.2.13 on 2022-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20220522_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writing',
            name='email',
        ),
        migrations.AddField(
            model_name='writing',
            name='소속',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='writing',
            name='신분',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='writing',
            name='최종학력',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='writing',
            name='technical_field',
            field=models.CharField(choices=[('기타', '기타'), ('웹', '웹'), ('앱', '앱'), ('인공지능', '인공지능'), ('게임', '게임')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='writing',
            name='topic_area',
            field=models.CharField(choices=[('금융/핀테크', '금융/핀테크'), ('공공/교통', '공공/교통'), ('생활', '생활'), ('유통/쇼핑', '유통/쇼핑'), ('기타', '기타'), ('의료', '의료'), ('엔터테인먼트', '엔터테인먼트'), ('업무', '업무'), ('교육', '교육')], default='', max_length=80),
        ),
    ]
