# Generated by Django 3.2.13 on 2022-05-28 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0008_auto_20220527_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writing',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='writing',
            name='technical_field',
            field=models.CharField(choices=[('앱', '앱'), ('기타', '기타'), ('웹', '웹'), ('인공지능', '인공지능'), ('게임', '게임')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='writing',
            name='topic_area',
            field=models.CharField(choices=[('교육', '교육'), ('공공/교통', '공공/교통'), ('기타', '기타'), ('금융/핀테크', '금융/핀테크'), ('엔터테인먼트', '엔터테인먼트'), ('생활', '생활'), ('의료', '의료'), ('업무', '업무'), ('유통/쇼핑', '유통/쇼핑')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='writing',
            name='신분',
            field=models.CharField(choices=[('취준생', '취준생'), ('직장인', '직장인'), ('기타', '기타'), ('학생', '학생')], default='', max_length=200),
        ),
    ]
