# Generated by Django 3.2.13 on 2022-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20220528_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writing',
            name='소속',
        ),
        migrations.AlterField(
            model_name='writing',
            name='technical_field',
            field=models.CharField(choices=[('게임', '게임'), ('웹', '웹'), ('인공지능', '인공지능'), ('앱', '앱'), ('기타', '기타')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='writing',
            name='topic_area',
            field=models.CharField(choices=[('금융/핀테크', '금융/핀테크'), ('교육', '교육'), ('의료', '의료'), ('공공/교통', '공공/교통'), ('생활', '생활'), ('업무', '업무'), ('유통/쇼핑', '유통/쇼핑'), ('기타', '기타'), ('엔터테인먼트', '엔터테인먼트')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='writing',
            name='신분',
            field=models.CharField(choices=[('기타', '기타'), ('취준생', '취준생'), ('직장인', '직장인'), ('학생', '학생')], default='', max_length=200),
        ),
    ]
